version: '3'

services:

  sanic_web:
    container_name: sanic_web
    build: .
    command: sh -c "python server.py"
    volumes:
      - .:/code
    ports:
      - "1337:1337"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

  nginx:
    container_name: sanic_nginx
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - sanic_web

  postgres:
    container_name: frameworks_postgres
    image: postgres:latest
    volumes:
      - frameworks_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  frameworks_postgres:
