version: '3'

services:

  falcon_web:
    container_name: falcon_web
    build: .
    command: sh -c "uwsgi uwsgi.ini"
    volumes:
      - .:/code
    ports:
      - "3031:3031"
      - "9191:9191"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONDEVMODE=1

  nginx:
    container_name: falcon_nginx
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - falcon_web

  postgres:
    container_name: falcon_postgres
    image: postgres:latest
    volumes:
      - falcon_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  falcon_postgres:
