version: '3'

services:

  fastapi_web:
    container_name: fastapi_web
    build: .
    command: sh -c "uvicorn --host 0.0.0.0 --port 8000 --workers 4 main:app"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

  nginx:
    container_name: fastapi_nginx
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi_web

  postgres:
    container_name: fastapi_postgres
    image: postgres:latest
    volumes:
      - fastapi_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  fastapi_postgres:
